### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_client#47]
Remove the deprecated methods that make requests for kalibro_processor.
See here: https://github.com/mezuro/kalibro_client/blob/master/lib/kalibro_client/entities/processor/processing.rb
We should use those methods on the Repository class.

**Comment by TomazMartins** [comment]
I will work on this issue.

**Comment by rafamanzo** [comment]
Merged. Thanks.

**Comment by TomazMartins** [comment]
Thank you for receive my contribution.
