### ISSUE TITLE
Handle HTTP codes for errors instead of returning possibly broken responses

### ISSUE THREAD

**Issue by marcheing** [mezuro/kalibro_client#60]
Right now we simply return whatever response we get in a request, even if the HTTP code indicates an error happened. That is a bad thing since there's no guarantee that the response makes sense if the code does not represent success.

That, for example, allows methods like `Repository#cancel_processing_of_repository` to fail silently even in case of an internal server error (like in mezuro/kalibro_processor#120).

This might be API-breaking behavior, but it's quite important to fix since it can allow errors to creep in silently to the user.

**Comment by rafamanzo** [comment]
Closed by https://github.com/mezuro/kalibro_client/pull/78.
