### ISSUE TITLE
Granularity instantiation

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_client#85]
Currently, when we instantiate a Granularity, the [hash converter](https://github.com/mezuro/kalibro_client/blob/master/lib/kalibro_client/helpers/hash_converters.rb#L29) will return a string because a Granularity do not inherit from `Miscellaneous::Base`.

Granularities are only instantiated [here](https://github.com/mezuro/kalibro_client/blob/master/lib/kalibro_client/entities/processor/module_result.rb#L42). But the string returned will cause an error on Prezento because it expects the `kalibro_module#granularity` to return the Granularity's type.

To solve this, we must first modify the `hash_converter` to handle Granularities and override `kalibro_module#granularity` to return the Granularity's type.

**Comment by diegoamc** [comment]
This issue is being fixed on this [branch](https://github.com/mezuro/kalibro_client/tree/fix_kalibro_module_granularity).

**Comment by rafamanzo** [comment]
Closed by: https://github.com/mezuro/kalibro_client/commit/4700fe59d5a17b6ae2e8acfe23c1f49cf0587b36
